### ISSUE TITLE
Clear Cart Session on process_payment

### ISSUE THREAD

**Issue by abdusfauzi** [wzul/WZ-SenangPay-for-WooCommerce#1]
Maybe, you should include `WC()->cart->empty_cart();` in the `process_payment()` so that user will not be confused with submitted order (WooCommerce [pending]) with cache the cart session?

Checkout -> Click pay -> create order -> empty cart -> redirect to senangPay

👍  Good work.

**Comment by wzul** [comment]
Some people happy with this current settings. But, some people may want to empty cart. So, I have provided an option for the web admin to enable or disable this feature.

Thank you! 👍

**Comment by abdusfauzi** [comment]
Nice solution.
