### ISSUE TITLE
Wrong form label in Setting page

### ISSUE THREAD

**Issue by abdusfauzi** [wzul/WZ-SenangPay-for-WooCommerce#2]
It seems that the Billplz plugin form label was still there. Ops.
- API Secret Key -> Merchant ID
- Collection ID -> Secret Key

![screen shot 2017-01-30 at 18 32 44](https://cloud.githubusercontent.com/assets/1118229/22419958/d29d4754-e71a-11e6-8d3f-d7510c2f9f86.png)

**Comment by wzul** [comment]
Ops. 

This module is developed based on Billplz plugin. I have corrected it. 

Thanks for for noticing! 🥇
