### ISSUE TITLE
[Request] Banking icon/logo at Checkout payment option selection.

### ISSUE THREAD

**Issue by abdusfauzi** [wzul/WZ-SenangPay-for-WooCommerce#3]
Would it be possible, to include series of icon or banks' logo at the Checkout page, where you select the payment option? Including senangPay branding logo?

Thank you.

**Comment by wzul** [comment]
I'm referring to your plugin [Billplz for WooCommerce](http://abdusfauzi.com). 

Yes it is possible. 

For the senangPay branding logo, I have integrated it.

But, I have problem with series of icon or banks' logo to place it. Could you suggest me the url which I can use it for that?

Appreciate your concern. Thank you! 🥇

**Comment by wzul** [comment]
![icon](https://cloud.githubusercontent.com/assets/19372567/22422999/815ee1ee-e72a-11e6-9441-74aed6b24c73.png)

**Comment by wzul** [comment]
Update: 

I don't believe we need to force the web admin to use the picture that we provide. So, I insert the code for as default values and it's up to the user if they want to use or remove it.

Setting page: 

![screenshot_20170130_221247](https://cloud.githubusercontent.com/assets/19372567/22426335/d7bfd5fc-e739-11e6-98e9-06479ff6aab0.png)

Checkout page:

![screenshot_20170130_221303](https://cloud.githubusercontent.com/assets/19372567/22426378/f78bef06-e739-11e6-9c4a-c3ab0c60b1bd.png)

**Comment by abdusfauzi** [comment]
@wzul agree. fast update 💪
