### ISSUE TITLE
Callback require to print OK for successful post request

### ISSUE THREAD

**Issue by abdusfauzi** [wzul/WZ-SenangPay-for-WooCommerce#4]
Tested the plugin on one of my current client. It seems that the plugin missing the response 'OK' needed as per mentioned in their Guide.

Failure to do so, will result with bombardment of emails from SenangPay server to the user account, stating that the **Callback** has failed.

![img_2017-02-04 13 03 26](https://cloud.githubusercontent.com/assets/1118229/22615880/9652ed1c-eada-11e6-83f1-1d42ac6b6152.jpeg)

Read here, under **Parameters** http://guide.senangpay.my/callback-url/

**Comment by wzul** [comment]
Previously, the callback will print RECEIVEOK instead of OK. This was corrected to OK in version 1.01. Please update and inform me if the problem still occur.

Thanks!

**Comment by wzul** [comment]
This issue considered as solved as it has been confirmed by SenangPay with increased of timeout for wp_safe_remote_get.
